//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExercisesList
    {
        public int ClientId { get; set; }
        public int ExercisesId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Exercises Exercises { get; set; }
    }
}
