//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileClientView
    {
        public int ClientId { get; set; }
        public string ClientFullName { get; set; }
        public Nullable<bool> ClientGender { get; set; }
        public byte[] Photo { get; set; }
    }
}
