//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсач.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        public int ClientId { get; set; }
        public byte[] PassportSeria { get; set; }
        public byte[] PassportNumber { get; set; }
        public string PassportWho { get; set; }
        public System.DateTime PassportDate { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
